### ISSUE TITLE
Request()['body'] includes response headers

### ISSUE THREAD

**Issue by tobiasmuehl** [peterkahl/curlMaster#2]
`echo $curlm->Request('https://someurl')['body']`

=> 

```html
HTTP/1.1 200 OK Server: nginx/1.15.8 Date: Sun, 10 Feb 2019 08:19:47 GMT Content-Type: application/json;charset=utf-8 Content-Length: 25329 Actual content starts here ....
```

Not ideal to have the headers printed out like this.

**Comment by peterkahl** [comment]
The method that parses the response body is--
`
  /**
   * Parses body from string
   * @param  string $str
   * @return string
   */
  private function getBody($str) {
    $str = substr($str, strpos($str, "\r\n\r\n"));
    return trim($str);
  }
`
... hence, I would assume that your issue is the EOL characters. I don't have the problem you mentioned, I use Linux server. Which OS does your server use?

**Comment by peterkahl** [comment]
@tobiasmuehl The most recent pull has the fix, so that EOL adjusts to the platform on which the library is used and I assume that this will address your issue. Please let me know.

**Comment by tobiasmuehl** [comment]
Thanks for the updates, will check later today. Server is on Ubuntu.
